/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "accent-pink-soft": "#fde0f0",
        "text-secondary": "#555a6a",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#713700",
        "tertiary-fixed": "#ffdcc6",
        "accent-coral-light": "#ffc6c6",
        "on-surface": "#1a1b23",
        "on-secondary-container": "#636264",
        "on-error-container": "#93000a",
        "on-surface-variant": "#444654",
        "on-primary-fixed-variant": "#0a33c0",
        "inverse-on-surface": "#f1effb",
        "tertiary-fixed-dim": "#ffb784",
        "secondary": "#5f5e60",
        "surface-primary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed": "#dee1ff",
        "surface-container": "#eeedf8",
        "surface-container-highest": "#e2e1ed",
        "action-pressed": "#2a41b6",
        "accent-rose-light": "#ffd8f4",
        "background": "#fbf8ff",
        "secondary-fixed": "#e4e2e4",
        "accent-red-light": "#fbd4d4",
        "surface-bright": "#fbf8ff",
        "surface-container-low": "#f4f2fe",
        "surface": "#fbf8ff",
        "outline-variant": "#c5c5d7",
        "primary-fixed-dim": "#bac3ff",
        "on-tertiary": "#ffffff",
        "primary": "#2f4dd5",
        "on-secondary-fixed-variant": "#474649",
        "on-primary": "#ffffff",
        "accent-moss-dark": "#187574",
        "text-primary": "#1c1c1e",
        "on-primary-fixed": "#001159",
        "surface-variant": "#e2e1ed",
        "success": "#00b473",
        "secondary-fixed-dim": "#c8c6c8",
        "border-standard": "#c7cad5",
        "on-secondary": "#ffffff",
        "primary-container": "#4c68ef",
        "surface-container-high": "#e8e7f3",
        "accent-teal-light": "#c3faf5",
        "tertiary": "#914800",
        "tertiary-container": "#b65c00",
        "error": "#ba1a1a",
        "accent-teal-dark": "#187574",
        "inverse-primary": "#bac3ff",
        "secondary-container": "#e2dfe1",
        "border-ring": "rgba(224, 226, 232, 1)",
        "on-background": "#1a1b23",
        "on-tertiary-fixed": "#301400",
        "on-primary-container": "#fffbff",
        "surface-tint": "#324fd8",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "accent-coral-dark": "#600000",
        "accent-orange-light": "#ffe6cd",
        "surface-dim": "#dad9e4",
        "accent-yellow-dark": "#746019",
        "inverse-surface": "#2f3039",
        "outline": "#757686",
        "on-secondary-fixed": "#1b1b1d",
        "placeholder": "#a5a8b5"
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px'
      },
      spacing: {
        'md': '12px',
        'xs': '4px',
        'gutter': '20px',
        'lg': '16px',
        'sm': '8px',
        'container-margin': '32px',
        'xl': '24px'
      },
      fontFamily: {
        'display-hero': ['Epilogue'],
        'feature-label': ['Epilogue'],
        'sub-heading': ['Inter'],
        'section-heading': ['Epilogue'],
        'card-title': ['Epilogue'],
        'button-text': ['Epilogue'],
        'caption': ['Epilogue'],
        'body-standard': ['Inter'],
        'body-large': ['Inter'],
        'micro-uppercase': ['Epilogue']
      },
      fontSize: {
        'display-hero': ['56px', { lineHeight: '1.15', letterSpacing: '-1.68px', fontWeight: '500' }],
        'feature-label': ['16px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '600' }],
        'sub-heading': ['22px', { lineHeight: '1.35', letterSpacing: '-0.44px', fontWeight: '400' }],
        'section-heading': ['48px', { lineHeight: '1.15', letterSpacing: '-1.44px', fontWeight: '500' }],
        'card-title': ['24px', { lineHeight: '1.15', letterSpacing: '-0.72px', fontWeight: '500' }],
        'button-text': ['17.5px', { lineHeight: '1.29', letterSpacing: '0.175px', fontWeight: '700' }],
        'caption': ['14px', { lineHeight: '1.71', letterSpacing: '0', fontWeight: '400' }],
        'body-standard': ['16px', { lineHeight: '1.50', letterSpacing: '-0.16px', fontWeight: '400' }],
        'body-large': ['18px', { lineHeight: '1.45', letterSpacing: '0', fontWeight: '400' }],
        'micro-uppercase': ['10.5px', { lineHeight: '0.90', letterSpacing: '0.05em', fontWeight: '400' }]
      }
    },
  },
  plugins: [],
}
